# visibilityCheck checks if a player can see another player (for Vanish plugins)
visibilityCheck: true

# formatting allows players to use the formatting codes (https://minecraft.wiki/w/Formatting_codes)
formatting: true

# selfMsg allows players to message themselves.
selfMsg: true

msgs: # Formatted with MiniMessage (https://docs.advntr.dev/minimessage/format.html)
  to: '<c:#b49bc7><i>You whisper to %p:</i> '
  from: '<c:#b49bc7><i>%p whispers to you:</i> '
  notfound: <red>Player not found.
  usage: <red>Invalid or insufficient arguments. Try <i>
  self: <red>You can't message yourself. # selfMsg must be set to false
  reload: <green>Message Reload complete.