# canSeeCheck is a small check that may improve compatibility with many Vanish plugins
canSeeCheck: true

# allowFormatting means that players can use the formatting codes (https://minecraft.wiki/w/Formatting_codes)
allowFormatting: true

# selfMsg allows players to message themselves.
selfMsg: true

msgs:
  to: "§oYou whispered to %p: "
  from: "§o%p whispered to you: "
  notfound: "§cPlayer not found."
  usage: "§cInvalid or insufficient arguments. Try §o"
  self: "§cYou can't message yourself." # Only when selfMsg = false