# canSeeCheck is a small check that may improve compatibility with many Vanish plugins
canSeeCheck: true

msgs:
  to: "§oYou whispered to %p: "
  from: "§o%p whispered to you: "
  notfound: "§cPlayer not found."
  usage: "§cInvalid or insufficient arguments. Try §o"